In [1]:
import cv2
import mediapipe as mp
import csv

import numpy as np
import pandas as pd
#
# mp_drawing = mp.solutions.drawing_utils
# mp_drawing_styles = mp.solutions.drawing_styles
# mp_hands = mp.solutions.hands
#
# dataframe = None
#
# cap = cv2.VideoCapture(0)
# with mp_hands.Hands(
#         model_complexity=0,
#         min_detection_confidence=0.5,
#         min_tracking_confidence=0.5) as hands:
#     while cap.isOpened():
#         success, image = cap.read()
#         if not success:
#             print("Ignoring empty camera frame.")
#             # If loading a video, use 'break' instead of 'continue'.
#             continue
#
#         # To improve performance, optionally mark the image as not writeable to
#         # pass by reference.
#         image.flags.writeable = False
#         image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#         results = hands.process(image)
#
#         # Draw the hand annotations on the image.
#         image.flags.writeable = True
#         image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
#
#         landmarks_hand = {}
#
#         if results.multi_hand_landmarks:
#
#             for index, landmark in enumerate(results.multi_hand_landmarks[0].landmark):
#                 x = landmark.x
#                 y = landmark.y
#                 z = landmark.z
#
#                 landmarks_hand[f'landmark_{index}_x'] = x
#                 landmarks_hand[f'landmark_{index}_y'] = y
#                 landmarks_hand[f'landmark_{index}_z'] = z
#
#             new_dataframe = pd.DataFrame(landmarks_hand, index=range(len(landmarks_hand.values())))
#             new_dataframe['target'] = 2
#
#             if dataframe is not None:
#                 dataframe = pd.concat((dataframe, new_dataframe))
#             else:
#                 dataframe = new_dataframe.copy()
#
#             dataframe.to_csv('datasets/scissor.csv', header=True, index=None)
#
#         # Flip the image horizontally for a selfie-view display.
#         cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
#
#         if cv2.waitKey(5) & 0xFF == 27:
#             break
#
# cap.release()
# cv2.destroyAllWindows()

In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

rock = pd.read_csv('datasets/rock.csv')
scissor = pd.read_csv('datasets/scissor.csv')
paper = pd.read_csv('datasets/paper.csv')

original_dataframe = pd.concat((rock, paper, scissor))
original_dataframe = original_dataframe.sample(frac=1)

x = original_dataframe.drop('target', axis=1)
y = original_dataframe['target']

one_hot = OneHotEncoder(sparse_output=False)
y = one_hot.fit_transform(y.to_numpy().reshape(-1, 1))

print(y)
train_x, test_x, train_y, test_y = train_test_split(x, y, train_size=0.7)

test_x, ev_x, test_y, ev_y = train_test_split(x, y, train_size=0.7)

train_x

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


landmark_0_x  landmark_0_y  landmark_0_z  landmark_1_x  landmark_1_y  \
2091      0.259880      0.718616 -7.395191e-09      0.315999      0.661813   
1226      0.323546      0.646133  1.781516e-09      0.396208      0.666009   
4505      0.196900      0.717888  2.353875e-08      0.289232      0.711417   
2979      0.263417      0.873160 -4.279606e-09      0.336139      0.916796   
28        0.045223      0.867703  7.977726e-09      0.134415      0.850254   
...            ...           ...           ...           ...           ...   
303       0.158857      0.809667 -5.348196e-10      0.211934      0.826210   
3780      0.201661      0.910321  1.419956e-08      0.181596      0.747530   
1501      0.254250      0.725288  1.214137e-08      0.351195      0.685697   
641       0.337069      0.671287  7.755495e-09      0.322978      0.577383   
5569      0.321310      0.676830 -6.645490e-09      0.386508      0.719450   

      landmark_1_z  landmark_2_x  landmark_2_y  landmark_2_z  landmark_3_x  \
2091     -0.041929      0.343533      0.567392     -0.092445      0.317869   
1226     -0.041564      0.477967      0.574853     -0.049162      0.492521   
4505     -0.091002      0.364870      0.659156     -0.161918      0.425242   
2979     -0.049576      0.394618      0.926390     -0.104429      0.391686   
28       -0.049195      0.196680      0.771972     -0.060397      0.231370   
...            ...           ...           ...           ...           ...   
303      -0.057776      0.258934      0.776542     -0.106172      0.247559   
3780      0.097587      0.215379      0.658554      0.119648      0.270224   
1501     -0.033605      0.431293      0.612948     -0.066773      0.493455   
641       0.074658      0.339835      0.498661      0.099559      0.380532   
5569     -0.056604      0.475144      0.715216     -0.082739      0.523845   

      ...  landmark_17_z  landmark_18_x  landmark_18_y  landmark_18_z  \
2091  ...      -0.167427       0.235774       0.609886      -0.205680   
1226  ...      -0.021132       0.335030       0.428597      -0.037826   
4505  ...      -0.162203       0.064267       0.389431      -0.218985   
2979  ...      -0.159569       0.295976       0.764709      -0.193082   
28    ...       0.012851       0.003400       0.579279      -0.011681   
...   ...            ...            ...            ...            ...   
303   ...      -0.129145       0.134556       0.691431      -0.166409   
3780  ...      -0.052303       0.360946       0.681247       0.018128   
1501  ...      -0.115875       0.154929       0.363016      -0.143876   
641   ...      -0.041275       0.459821       0.498589      -0.008379   
5569  ...      -0.063160       0.429374       0.479395      -0.086498   

      landmark_19_x  landmark_19_y  landmark_19_z  landmark_20_x  \
2091       0.288974       0.659977      -0.205095       0.316659   
1226       0.333588       0.506293      -0.035486       0.332475   
4505       0.027870       0.332390      -0.255592       0.001277   
2979       0.279978       0.835784      -0.196676       0.274712   
28         0.006675       0.525658      -0.035229       0.009887   
...             ...            ...            ...            ...   
303        0.142683       0.761675      -0.170069       0.147386   
3780       0.337450       0.715490       0.070214       0.323698   
1501       0.122884       0.302378      -0.164699       0.097286   
641        0.451756       0.538904       0.007469       0.432532   
5569       0.401299       0.538532      -0.085045       0.410353   

      landmark_20_y  landmark_20_z  
2091       0.690164      -0.200432  
1226       0.526006      -0.025577  
4505       0.273081      -0.285465  
2979       0.872989      -0.194551  
28         0.480943      -0.050859  
...             ...            ...  
303        0.804038      -0.167626  
3780       0.748856       0.101228  
1501       0.237445      -0.183290  
641        0.553627       0.010893  
5569       0.554334      -0.076

In [3]:
from keras.layers import MaxPooling2D, Flatten, Dense, Dropout, Convolution2D
from keras import Sequential
import tensorflow as tf

model = Sequential()
model.add(Dense(63, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))


In [4]:
print(x.shape)

(18333, 63)


In [5]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['Accuracy'])

In [6]:
model.fit(train_x, train_y, validation_data=(test_x, test_y), epochs=10)

Epoch 1/10
402/402 [==============================] - 1s 2ms/step - loss: 0.3599 - Accuracy: 0.9303 - val_loss: 0.0512 - val_Accuracy: 0.9964
Epoch 2/10
402/402 [==============================] - 1s 1ms/step - loss: 0.0257 - Accuracy: 0.9974 - val_loss: 0.0137 - val_Accuracy: 0.9964
Epoch 3/10
402/402 [==============================] - 1s 1ms/step - loss: 0.0091 - Accuracy: 0.9992 - val_loss: 0.0058 - val_Accuracy: 1.0000
Epoch 4/10
402/402 [==============================] - 1s 1ms/step - loss: 0.0053 - Accuracy: 0.9995 - val_loss: 0.0031 - val_Accuracy: 1.0000
Epoch 5/10
402/402 [==============================] - 0s 1ms/step - loss: 0.0027 - Accuracy: 1.0000 - val_loss: 0.0019 - val_Accuracy: 1.0000
Epoch 6/10
402/402 [==============================] - 1s 1ms/step - loss: 0.0017 - Accuracy: 1.0000 - val_loss: 0.0012 - val_Accuracy: 1.0000
Epoch 7/10
402/402 [==============================] - 0s 1ms/step - loss: 0.0011 - Accuracy: 1.0000 - val_loss: 8.3340e-04 - val_Accuracy: 1.0000
Ep

In [7]:
predict = ev_x.iloc[0].to_numpy().reshape(1, -1)
print(model.predict(predict))
print(ev_y[0])

predict = ev_x.iloc[10].to_numpy().reshape(1, -1)
print(model.predict(predict))
print(ev_y[10])

predict = ev_x.iloc[13].to_numpy().reshape(1, -1)
print(model.predict(predict))
print(ev_y[13])

1/1 [==============================] - 0s 58ms/step
[[9.9991632e-01 4.3164032e-06 7.9348756e-05]]
[1. 0. 0.]
1/1 [==============================] - 0s 14ms/step
[[9.9835497e-01 1.9592517e-05 1.6254087e-03]]
[1. 0. 0.]
1/1 [==============================] - 0s 14ms/step
[[2.7660133e-07 9.9999833e-01 1.4740193e-06]]
[0. 1. 0.]


In [18]:
import numpy as np

def get_machine_move():
    return np.random.choice([0,1,2])

def check_move(imagen, machine_move, prediction):
    if machine_move == 0:
        if prediction == 0:
            text = 'hemos empatado yo he sacado' + type_predict[machine_move]

            cv2.putText(imagen, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

            return text

        elif prediction == 1:
            text = 'has ganado yo he sacado ' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

            return text

        else:
            text = 'has perdido yo he sacado ' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)
            return text

    elif machine_move == 1:
        if prediction == 0:
            text = 'has perdido yo he sacado ' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

            return text

        elif prediction == 1:
            text = 'hemos empatado yo he sacado' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

            return text
        else:
            text = 'has ganado yo he sacado' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)
            return text

    else:
        if prediction == 0:
            text = 'has ganado yo he sacado' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)
            return text

        elif prediction == 1:
            text = 'has perdido yo he sacado' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)
            return text
        else:
            text = 'hemos empatado yo he sacado' + type_predict[machine_move]

            cv2.putText(image, text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

            return text


mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands
type_predict = {0: 'rock', 1:'paper', 2:'scissors'}
image_predict = {0: cv2.imread("filtros/piedra.jpg"), 1:cv2.imread("filtros/paper.jpg"), 2:cv2.imread("filtros/tijeras.jpg")}
font = cv2.FONT_HERSHEY_SIMPLEX
fontScale = 1
color = (0, 0, 0)
thickness = 1
wait = False
dataframe = None
count = 0
cap = cv2.VideoCapture(0)
timer = 3
wait_5_seconds = False
win_text = ''
win_image = np.array([])

with mp_hands.Hands(
        model_complexity=0,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:

    while cap.isOpened():
        count += 1
        success, image = cap.read()

        image = cv2.flip(image, 1)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        cv2.putText(image, str(timer), (int(image.shape[1]/2), int(image.shape[0]/2)), font, fontScale, color, thickness, cv2.LINE_AA)

        if wait_5_seconds and count < 200:
            cv2.putText(image, win_text, (0, 100), font,
                            fontScale, color, thickness, cv2.LINE_AA)

        elif count >= 200 and wait_5_seconds:
            wait_5_seconds = False
            count = 0
            timer = 3
            win_text = ''
            win_image = np.array([])

        if count >= 30 and timer > 0:
            timer-=1
            count = 0

        if timer == 0 and not wait_5_seconds:
            results = hands.process(image)

            landmarks_hand = {}

            if results.multi_hand_landmarks:

                for index, landmark in enumerate(results.multi_hand_landmarks[0].landmark):
                    x = landmark.x
                    y = landmark.y
                    z = landmark.z

                    landmarks_hand[f'landmark_{index}_x'] = x
                    landmarks_hand[f'landmark_{index}_y'] = y
                    landmarks_hand[f'landmark_{index}_z'] = z

                machine_move = get_machine_move()

                predict = np.array(list(landmarks_hand.values())).reshape(1, -1)
                predict = np.argmax(model.predict(predict))
                print(predict)
                win_text = check_move(image, machine_move, predict)

                win_image = image_predict[machine_move]
                win_image = cv2.resize(win_image, (200, 200))
                cv2.imshow('Machine', win_image)

                count = 0
                wait_5_seconds = True

        cv2.imshow('MediaPipe Hands', image)
        if cv2.waitKey(5) & 0xFF == 27:
            break

cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 14ms/step
0
1/1 [==============================] - 0s 14ms/step
0
1/1 [==============================] - 0s 13ms/step
2
1/1 [==============================] - 0s 13ms/step
0
1/1 [==============================] - 0s 14ms/step
1
1/1 [==============================] - 0s 14ms/step
0
1/1 [==============================] - 0s 13ms/step
1
1/1 [==============================] - 0s 13ms/step
2
1/1 [==============================] - 0s 13ms/step
0
1/1 [==============================] - 0s 14ms/step
1


KeyboardInterrupt: 